# Generated by Django 6.0.2 on 2026-04-07 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Набор правил доступа',
                'verbose_name_plural': 'Наборы правил доступа',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('user', 'Пользователи')], max_length=50, verbose_name='Ресурс')),
                ('action', models.CharField(choices=[('view', 'Просмотр'), ('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('change_password', 'Смена пароля')], max_length=50, verbose_name='Действие')),
                ('subject_level', models.PositiveSmallIntegerField(verbose_name='Для уровня')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='Разрешено')),
                ('scope', models.CharField(choices=[('none', 'Ничего'), ('own_unit', 'Только своё подразделение'), ('descendants', 'Только дочерние подразделения'), ('own_and_descendants', 'Своё и дочерние подразделения'), ('all', 'Все подразделения')], default='none', max_length=50, verbose_name='Scope записей')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='access_control.accessruleset', verbose_name='Набор правил')),
            ],
            options={
                'verbose_name': 'Правило доступа',
                'verbose_name_plural': 'Правила доступа',
                'ordering': ['resource', 'action', 'subject_level', 'priority', 'id'],
                'indexes': [models.Index(fields=['ruleset', 'resource', 'action', 'subject_level'], name='access_cont_ruleset_e6728e_idx'), models.Index(fields=['is_active', 'priority'], name='access_cont_is_acti_e2cb51_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('user', 'Пользователи')], max_length=50, verbose_name='Ресурс')),
                ('action', models.CharField(choices=[('view', 'Просмотр'), ('create', 'Создание'), ('update', 'Редактирование')], max_length=50, verbose_name='Действие')),
                ('subject_level', models.PositiveSmallIntegerField(verbose_name='Для уровня')),
                ('field_name', models.CharField(max_length=100, verbose_name='Поле')),
                ('can_view', models.BooleanField(default=True, verbose_name='Можно видеть')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Можно редактировать')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rules', to='access_control.accessruleset', verbose_name='Набор правил')),
            ],
            options={
                'verbose_name': 'Правило доступа к полю',
                'verbose_name_plural': 'Правила доступа к полям',
                'ordering': ['resource', 'action', 'field_name', 'subject_level', 'priority', 'id'],
                'indexes': [models.Index(fields=['ruleset', 'resource', 'action', 'subject_level'], name='access_cont_ruleset_964963_idx'), models.Index(fields=['field_name', 'is_active'], name='access_cont_field_n_051f46_idx')],
            },
        ),
    ]
