# Generated by Django 6.0.2 on 2026-04-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessfieldrule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники')], max_length=50, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='action',
            field=models.CharField(choices=[('view', 'Просмотр'), ('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('change_password', 'Смена пароля'), ('manage_exemptions', 'Управление освобождениями'), ('manage_clearances', 'Управление допусками')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники')], max_length=50, verbose_name='Ресурс'),
        ),
    ]
