# Generated by Django 6.0.2 on 2026-04-07 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_alter_accessfieldrule_resource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessChoiceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники')], max_length=50, verbose_name='Ресурс')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование')], max_length=50, verbose_name='Действие')),
                ('subject_level', models.PositiveSmallIntegerField(verbose_name='Для уровня')),
                ('field_name', models.CharField(max_length=100, verbose_name='Поле select/queryset')),
                ('scope', models.CharField(choices=[('none', 'Ничего'), ('own_unit', 'Только своё подразделение'), ('descendants', 'Только дочерние подразделения'), ('own_and_descendants', 'Своё и дочерние подразделения'), ('all', 'Все подразделения')], default='none', max_length=50, verbose_name='Scope значений')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Приоритет')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_rules', to='access_control.accessruleset', verbose_name='Набор правил')),
            ],
            options={
                'verbose_name': 'Правило доступа к выпадающему списку',
                'verbose_name_plural': 'Правила доступа к выпадающим спискам',
                'ordering': ['resource', 'action', 'field_name', 'subject_level', 'priority', 'id'],
                'indexes': [models.Index(fields=['ruleset', 'resource', 'action', 'field_name', 'subject_level'], name='access_cont_ruleset_dc9cf7_idx')],
            },
        ),
    ]
