# Generated by Django 6.0.2 on 2026-04-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_accesschoicerule'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesschoicerule',
            name='mode',
            field=models.CharField(choices=[('scope', 'По scope'), ('specific_units', 'Только конкретные подразделения'), ('scope_plus_units', 'Scope + конкретные подразделения')], default='scope', max_length=32, verbose_name='Режим выбора'),
        ),
        migrations.AddField(
            model_name='accesschoicerule',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='access_choice_rules', to='units.unit', verbose_name='Конкретные подразделения'),
        ),
        migrations.AlterField(
            model_name='accesschoicerule',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('manage_clearances', 'Управление допусками')], max_length=50, verbose_name='Действие'),
        ),
    ]
