# Generated by Django 6.0.2 on 2026-04-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_expand_unit_resource_choices'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesschoicerule',
            name='unit_types',
            field=models.ManyToManyField(blank=True, related_name='access_choice_rules', to='units.unittype', verbose_name='Конкретные типы подразделений'),
        ),
        migrations.AlterField(
            model_name='accesschoicerule',
            name='mode',
            field=models.CharField(choices=[('scope', 'По scope'), ('specific_units', 'Только конкретные подразделения'), ('scope_plus_units', 'Scope + конкретные подразделения'), ('all_values', 'Все значения'), ('specific_unit_types', 'Только конкретные типы подразделений')], default='scope', max_length=32, verbose_name='Режим выбора'),
        ),
    ]
