# Generated by Django 6.0.2 on 2026-04-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_accesschoicerule_unit_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesschoicerule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники'), ('unit', 'Подразделения'), ('unit_type', 'Типы подразделений')], max_length=50, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='accessfieldrule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники'), ('unit', 'Подразделения'), ('unit_type', 'Типы подразделений')], max_length=50, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники'), ('unit', 'Подразделения'), ('unit_type', 'Типы подразделений')], max_length=50, verbose_name='Ресурс'),
        ),
    ]
