# Generated by Django 6.0.2 on 2026-04-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_alter_accesschoicerule_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesschoicerule',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('manage_clearances', 'Управление допусками'), ('manage_days', 'Управление таблицей дней')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='accesschoicerule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники'), ('unit', 'Подразделения'), ('unit_type', 'Типы подразделений'), ('duty_type', 'Типы нарядов'), ('plan', 'Планы нарядов')], max_length=50, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='accessfieldrule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники'), ('unit', 'Подразделения'), ('unit_type', 'Типы подразделений'), ('duty_type', 'Типы нарядов'), ('plan', 'Планы нарядов')], max_length=50, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='action',
            field=models.CharField(choices=[('view', 'Просмотр'), ('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('change_password', 'Смена пароля'), ('manage_exemptions', 'Управление освобождениями'), ('manage_clearances', 'Управление допусками'), ('manage_days', 'Управление таблицей дней'), ('accept_incoming', 'Принятие входящих')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники'), ('unit', 'Подразделения'), ('unit_type', 'Типы подразделений'), ('duty_type', 'Типы нарядов'), ('plan', 'Планы нарядов')], max_length=50, verbose_name='Ресурс'),
        ),
    ]
