# Generated by Django 6.0.2 on 2026-04-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0008_alter_accesschoicerule_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesschoicerule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники'), ('unit', 'Подразделения'), ('unit_type', 'Типы подразделений'), ('duty_type', 'Типы нарядов'), ('plan', 'Планы нарядов'), ('assignment', 'Назначения сотрудников')], max_length=50, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='accessfieldrule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники'), ('unit', 'Подразделения'), ('unit_type', 'Типы подразделений'), ('duty_type', 'Типы нарядов'), ('plan', 'Планы нарядов'), ('assignment', 'Назначения сотрудников')], max_length=50, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='action',
            field=models.CharField(choices=[('view', 'Просмотр'), ('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('change_password', 'Смена пароля'), ('manage_exemptions', 'Управление освобождениями'), ('manage_clearances', 'Управление допусками'), ('manage_days', 'Управление таблицей дней'), ('accept_incoming', 'Принятие входящих'), ('assign', 'Назначение сотрудников'), ('unassign', 'Снятие назначений')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='resource',
            field=models.CharField(choices=[('user', 'Пользователи'), ('person', 'Сотрудники'), ('unit', 'Подразделения'), ('unit_type', 'Типы подразделений'), ('duty_type', 'Типы нарядов'), ('plan', 'Планы нарядов'), ('assignment', 'Назначения сотрудников')], max_length=50, verbose_name='Ресурс'),
        ),
    ]
