# Generated by Django 6.0.2 on 2026-04-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_alter_accesschoicerule_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesschoicerule',
            name='scope',
            field=models.CharField(choices=[('none', 'Ничего'), ('own_unit', 'Только своё подразделение'), ('children', 'Только прямые дочерние подразделения'), ('own_and_children', 'Своё и прямые дочерние подразделения'), ('all_descendants', 'Все дочерние подразделения по всей иерархии'), ('own_and_all_descendants', 'Своё и все дочерние подразделения по всей иерархии'), ('all', 'Все подразделения')], default='none', max_length=64, verbose_name='Scope значений'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='scope',
            field=models.CharField(choices=[('none', 'Ничего'), ('own_unit', 'Только своё подразделение'), ('children', 'Только прямые дочерние подразделения'), ('own_and_children', 'Своё и прямые дочерние подразделения'), ('all_descendants', 'Все дочерние подразделения по всей иерархии'), ('own_and_all_descendants', 'Своё и все дочерние подразделения по всей иерархии'), ('all', 'Все подразделения')], default='none', max_length=64, verbose_name='Scope записей'),
        ),
    ]
