# Generated by Django 6.0.2 on 2026-04-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0010_alter_accesschoicerule_scope_alter_accessrule_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessMenuRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(max_length=100, verbose_name='Ключ пункта меню')),
                ('subject_level', models.PositiveSmallIntegerField(verbose_name='Для уровня')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Приоритет')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_rules', to='access_control.accessruleset', verbose_name='Набор правил')),
            ],
            options={
                'verbose_name': 'Правило видимости пункта меню',
                'verbose_name_plural': 'Правила видимости пунктов меню',
                'ordering': ['subject_level', 'priority', 'menu_key', 'id'],
                'indexes': [models.Index(fields=['ruleset', 'subject_level', 'menu_key'], name='access_cont_ruleset_a5bf37_idx')],
                'unique_together': {('ruleset', 'menu_key', 'subject_level')},
            },
        ),
    ]
