# Generated by Django 6.0.2 on 2026-03-22 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duty_types', '0001_initial'),
        ('people', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('parent_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_schedules', to='duty_plans.monthlyschedule')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='units.unit', verbose_name='Подразделение')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('execution_type', models.CharField(choices=[('own', 'Своими силами'), ('delegate', 'Делегировать')], default='own', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duty_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty_types.dutytype')),
                ('parent_day_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='duty_plans.dayplan')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='duty_plans.monthlyschedule')),
            ],
            options={
                'unique_together': {('schedule', 'date', 'duty_type')},
            },
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duties', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='duty_plans.dayplan', verbose_name='План на день')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to='people.person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Назначение на наряд',
                'verbose_name_plural': 'Назначения на наряды',
                'unique_together': {('day_plan', 'person')},
            },
        ),
    ]
