# Generated by Django 6.0.2 on 2026-02-25 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duty_types', '0001_initial'),
        ('people', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата наряда')),
                ('duty_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_plans', to='duty_types.dutytype', verbose_name='Тип наряда')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_plans', to='units.unit', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'План наряда',
                'verbose_name_plural': 'Планы нарядов',
                'ordering': ['-date', 'unit'],
                'unique_together': {('date', 'unit', 'duty_type')},
            },
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to='people.person', verbose_name='Сотрудник')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='duty_plans.dutyplan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Назначение на наряд',
                'verbose_name_plural': 'Назначения на наряды',
                'unique_together': {('plan', 'person')},
            },
        ),
    ]
