# Generated by Django 6.0.2 on 2026-03-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayplan',
            options={'ordering': ['date'], 'verbose_name': 'План на день', 'verbose_name_plural': 'Планы на день'},
        ),
        migrations.RemoveField(
            model_name='dayplan',
            name='execution_type',
        ),
        migrations.RemoveField(
            model_name='dayplan',
            name='parent_day_plan',
        ),
        migrations.AddField(
            model_name='dayplan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='duty_plans.dayplan'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает принятия'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit', verbose_name='Подразделение-исполнитель'),
        ),
    ]
