# Generated by Django 6.0.2 on 2026-03-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyschedule',
            name='unit',
        ),
    ]
