# Generated by Django 6.0.2 on 2026-03-22 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0001_initial'),
        ('duty_types', '0002_dutytype_created_by_unit_dutytype_unit'),
        ('people', '0001_initial'),
        ('units', '0002_alter_unit_options_alter_unittype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата назначения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duties', to=settings.AUTH_USER_MODEL, verbose_name='Назначил'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_plans', to='duty_plans.dutyplan', verbose_name='Создан на основе плана'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='dutyassignment',
            index=models.Index(fields=['plan', 'person'], name='duty_plans__plan_id_696c07_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyplan',
            index=models.Index(fields=['date', 'unit'], name='duty_plans__date_6d6360_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyplan',
            index=models.Index(fields=['parent_plan'], name='duty_plans__parent__26ed82_idx'),
        ),
    ]
