# Generated by Django 6.0.2 on 2026-03-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0002_alter_dayplan_options_remove_dayplan_execution_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='type',
            field=models.CharField(choices=[('own', 'Свой наряд'), ('incoming', 'Входящий наряд')], default='own', max_length=20, verbose_name='Тип назначения'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает принятия'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
