# Generated by Django 6.0.2 on 2026-03-22 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0002_remove_monthlyschedule_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_day_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
    ]
