# Generated by Django 6.0.2 on 2026-03-22 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0003_alter_dayplan_created_by'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplan',
            name='created_by',
        ),
        migrations.AddField(
            model_name='dayplan',
            name='execution_type',
            field=models.CharField(choices=[('own', 'Силами своего аппарата'), ('delegate', 'Делегировать подразделению')], default='own', max_length=20, verbose_name='Способ исполнения'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='parent_day_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_plans', to='duty_plans.dayplan', verbose_name='Создано на основе назначения'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='duty_plans.monthlyschedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_day_plans', to='units.unit', verbose_name='Подразделение-исполнитель'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyschedule',
            unique_together={('month', 'created_by')},
        ),
    ]
