# Generated by Django 6.0.2 on 2026-03-22 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0003_dayplan_type_alter_dayplan_status'),
        ('duty_types', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='duty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty_types.dutytype', verbose_name='Тип наряда'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='duty_plans.dayplan', verbose_name='Родительское назначение'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='duty_plans.monthlyschedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает принятия'), ('accepted', 'Принято')], max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='dayplan',
            index=models.Index(fields=['schedule', 'date'], name='duty_plans__schedul_f300c7_idx'),
        ),
        migrations.AddIndex(
            model_name='dayplan',
            index=models.Index(fields=['type', 'status'], name='duty_plans__type_7f77c0_idx'),
        ),
        migrations.AddIndex(
            model_name='dayplan',
            index=models.Index(fields=['unit'], name='duty_plans__unit_id_3cc06f_idx'),
        ),
    ]
