# Generated by Django 6.0.2 on 2026-03-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0004_alter_dayplan_created_at_alter_dayplan_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='child_status',
            field=models.CharField(choices=[('none', 'Нет дочерних'), ('pending', 'Ожидает принятия'), ('accepted', 'Принято дочерним')], default='none', max_length=20, verbose_name='Статус дочернего'),
        ),
    ]
