# Generated by Django 6.0.2 on 2026-03-22 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0005_dayplan_child_status'),
        ('duty_types', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayplan',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='dayplan',
            name='duty_plans__unit_id_3cc06f_idx',
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='child_status',
            field=models.CharField(choices=[('none', 'Нет дочерних'), ('pending', 'Ожидает принятия'), ('accepted', 'Принято дочерним')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='duty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty_types.dutytype'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='duty_plans.dayplan'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='duty_plans.monthlyschedule'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает принятия'), ('accepted', 'Принято')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='type',
            field=models.CharField(choices=[('own', 'Свой наряд'), ('incoming', 'Входящий наряд')], default='own', max_length=20),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='monthlyschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyschedule',
            name='parent_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='duty_plans.monthlyschedule'),
        ),
        migrations.AlterField(
            model_name='monthlyschedule',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='units.unit'),
        ),
    ]
