# Generated by Django 6.0.2 on 2026-03-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0006_alter_dayplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dayplan',
            name='duty_plans__schedul_f300c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='dayplan',
            name='duty_plans__type_7f77c0_idx',
        ),
        migrations.AlterField(
            model_name='monthlyschedule',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='monthlyschedule',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
