# Generated by Django 6.0.2 on 2026-03-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty_plans', '0007_remove_dayplan_duty_plans__schedul_f300c7_idx_and_more'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyschedule',
            unique_together={('month', 'unit')},
        ),
    ]
