# Generated by Django 6.0.2 on 2026-03-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_type__level', 'name'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='unittype',
            options={'ordering': ['level', 'name'], 'verbose_name': 'Тип подразделения', 'verbose_name_plural': 'Типы подразделений'},
        ),
        migrations.AddField(
            model_name='unittype',
            name='can_have_children',
            field=models.BooleanField(default=True, verbose_name='Может иметь дочерние подразделения'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 - самый высокий уровень (академия), 1 - факультет, 2 - кафедра и т.д.', verbose_name='Уровень иерархии'),
        ),
    ]
