# Generated by Django 6.0.2 on 2026-03-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duty_types', '0001_initial'),
        ('ranks', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='ranks.rank', verbose_name='Звание')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='units.unit', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Exemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('illness', 'Болезнь'), ('leave', 'Отпуск'), ('trip', 'Командировка'), ('other', 'Другое')], max_length=20, verbose_name='Причина')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='people.person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Освобождение',
                'verbose_name_plural': 'Освобождения',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='DutyClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='duty_types.dutytype', verbose_name='Тип наряда')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='people.person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Допуск к наряду',
                'verbose_name_plural': 'Допуски к нарядам',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='people_pers_last_na_c63c6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dutyclearance',
            unique_together={('person', 'duty_type')},
        ),
    ]
