# Generated by Django 6.0.2 on 2026-02-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_types', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutytype',
            name='created_by_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duty_types', to='units.unit', verbose_name='Создано подразделением'),
        ),
        migrations.AddField(
            model_name='dutytype',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='duty_types', to='units.unit', verbose_name='Закрепленное подразделение'),
            preserve_default=False,
        ),
    ]
