# Generated by Django 6.0.2 on 2026-03-22 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('required_people', models.PositiveSmallIntegerField(default=1, verbose_name='Требуется человек')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_duty_types', to='units.unit', verbose_name='Создано подразделением')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duty_types', to='units.unit', verbose_name='Закрепленное подразделение (опционально)')),
            ],
            options={
                'verbose_name': 'Тип наряда',
                'verbose_name_plural': 'Типы нарядов',
                'ordering': ['name'],
            },
        ),
    ]
