# Generated by Django 6.0.2 on 2026-02-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('required_people', models.PositiveSmallIntegerField(default=1, verbose_name='Требуется человек')),
            ],
            options={
                'verbose_name': 'Тип наряда',
                'verbose_name_plural': 'Типы нарядов',
                'ordering': ['name'],
            },
        ),
    ]
