# Generated by Django 6.0.2 on 2026-03-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_types', '0002_alter_dutytype_unit'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutytype',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_types', to='units.unit', verbose_name='Закрепленное подразделение'),
        ),
    ]
